name: Address Sanitizer analysis

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'

jobs:

  asan-test:
    if: ${{ !(contains(github.event.pull_request.labels.*.name, 'no-test') ||
              contains(github.event.pull_request.labels.*.name, 'skip-ci')) }}
    runs-on: ubuntu-20.04

    steps:
      - name: Sync eProsima/Fast-DDS repository
        uses: actions/checkout@v3
        with:
          path: src/Fast-DDS

      - name: Install apt packages
        uses: ./src/Fast-DDS/.github/actions/install-apt-packages

      - name: Install GTest
        uses: ./src/Fast-DDS/.github/actions/install-gtest-linux

      - name: Install Python packages
        uses: ./src/Fast-DDS/.github/actions/install-python-packages

      - name: Fetch Fast DDS dependencies
        uses: ./src/Fast-DDS/.github/actions/fetch-fastdds-repos

      - name: Build workspace
        run: |
          cat src/Fast-DDS/.github/workflows/asan_colcon.meta
          colcon build \
            --event-handlers=console_direct+ \
            --metas src/Fast-DDS/.github/workflows/asan_colcon.meta

      - name: Run tests Fast DDS
        run: |
          source install/setup.bash && \
          colcon test \
            --packages-select fastrtps \
            --event-handlers=console_direct+ \
            --return-code-on-test-failure \
            --ctest-args \
              --label-exclude xfail \
              --timeout 60

      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: asan-logs
          path: log/
        if: always()

      - name: Report ASAN errors
        if: always()
        run: |
          echo -n "**ASAN Errors**: " >> $GITHUB_STEP_SUMMARY
          echo $(sed 's/==.*==ERROR:/==.*==ERROR:\n/g' log/latest_test/fastrtps/stdout_stderr.log | grep -c "==.*==ERROR:") >> $GITHUB_STEP_SUMMARY
          python3 src/Fast-DDS/.github/workflows/asan_log_parser.py
