name: Fast DDS Windows CI (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # At 22:00 GMT

jobs:
  nightly-windows-ci-master:
    strategy:
      fail-fast: false
      matrix:
        security:
          - 'ON'
          - 'OFF'
        cmake_build_type:
          - 'Debug'
          - 'RelWithDebInfo'
        test_filter:
          - 'blackbox'
          - 'unittest'
    uses: eProsima/Fast-DDS/.github/workflows/reusable-windows-ci.yml@master
    with:
      label: nightly-sec-${{ matrix.security }}-${{ matrix.cmake_build_type }}-${{ matrix.test_filter }}-windows-ci-master
      cmake-config: ${{ matrix.cmake_build_type }}
      cmake-args: "-DSECURITY=${{ matrix.security }}"
      ctest-args: -LE xfail ${{ matrix.test_filter == 'blackbox' && '-R "BlackboxTests|example_tests"' || matrix.test_filter == 'unittest' && '-E "BlackboxTests|example_tests" -j 4' }}
      fastdds_branch: 'master'
