name: Fast DDS Windows CI (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  nightly-sec-windows-ci:
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      label: 'nightly-sec-windows-ci'
      cmake-args: "-DSECURITY=ON"
      ctest-args: "-LE xfail"
      fastdds_branch: 'master'

  nightly-nosec-windows-ci:
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      label: 'nightly-nosec-windows-ci'
      cmake-args: "-DSECURITY=OFF"
      ctest-args: "-LE xfail"
      fastdds_branch: 'master'

  nightly-3_0_x-windows-ci:
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      label: 'nightly-3.0.x-windows-ci'
      cmake-args: "-DSECURITY=ON"
      ctest-args: "-LE xfail"
      fastdds_branch: '3.0.x-devel'
