name: Fast DDS Windows CI (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  nightly-sec-windows-ci:
    strategy:
      fail-fast: false
      matrix:
        fastdds-branch:
          - 'master'
          - '2.13.x'
          - '2.12.x'
          - '2.10.x'
          - '2.6.x'
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      label: 'nightly-sec-windows-ci-${{ matrix.fastdds-branch }}'
      cmake-args: "-DSECURITY=ON"
      ctest-args: "-LE xfail"
      fastdds_branch: '${{ matrix.fastdds-branch }}'

  nightly-nosec-windows-ci:
    strategy:
      fail-fast: false
      matrix:
        fastdds-branch:
          - 'master'
          - '2.13.x'
          - '2.12.x'
          - '2.10.x'
          - '2.6.x'
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      label: 'nightly-nosec-windows-ci-${{ matrix.fastdds-branch }}'
      cmake-args: "-DSECURITY=OFF"
      ctest-args: "-LE xfail"
      fastdds_branch: '${{ matrix.fastdds-branch }}'

  nightly-3_0_x-windows-ci:
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      label: 'nightly-3.0.x-windows-ci'
      cmake-args: "-DSECURITY=ON"
      ctest-args: "-LE xfail"
      fastdds_branch: '3.0.x-devel'
