name: Fast DDS MacOS CI (nightly 3.1.x)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # At 22:00 GMT

jobs:
  nightly-mac-ci-3_1_x:
    strategy:
      fail-fast: false
      matrix:
        security:
          - 'ON'
          - 'OFF'
    uses: eProsima/Fast-DDS/.github/workflows/reusable-mac-ci.yml@3.1.x
    with:
      label: 'nightly-sec-${{ matrix.security }}-mac-ci-3.1.x'
      cmake-args: "-DSECURITY=${{ matrix.security }} -DTHIRDPARTY_Asio=FORCE"
      ctest-args: "-LE xfail"
      fastdds-branch: '3.1.x'
      use-ccache: false
