name: statistics_coverage

on:
  workflow_dispatch:

jobs:
  ubuntu-build-test:
    runs-on: ubuntu-latest
    environment:
      name: codecov

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/Fast-DDS

      - uses: ./src/Fast-DDS/.github/actions/install-apt-packages
      - uses: ./src/Fast-DDS/.github/actions/install-python-packages
      - uses: ./src/Fast-DDS/.github/actions/fetch-fastdds-repos

      - name: Update colcon mixin
        run: |
          colcon mixin add default \
            https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon mixin update default
        continue-on-error: true

      - name: Build workspace
        run: |
          cat src/Fast-DDS/.github/workflows/statistics_module.meta
          colcon build \
            --packages-up-to fastrtps --packages-skip fastrtps \
            --event-handlers=console_direct+ \
            --metas src/Fast-DDS/.github/workflows/statistics_module.meta \
            --mixin coverage-gcc
          for target in RTPSStatisticsTests StatisticsDomainParticipantTests StatisticsQosTests DomainParticipantStatisticsListenerTests StatisticsDomainParticipantMockTests BlackboxTests_DDS_PIM
          do
              colcon build \
                --packages-select fastrtps \
                --cmake-target $target \
                --cmake-target-skip-unavailable \
                --event-handlers=console_direct+ \
                --metas src/Fast-DDS/.github/workflows/statistics_module.meta \
                --mixin coverage-gcc
          done

      - name: Run tests
        run: |
          colcon test \
            --packages-select fastrtps \
            --event-handlers=console_direct+ \
            --ctest-args -R RTPSStatisticsTests -R Statistics

      - name: Generate coverage report
        run: |
          cp src/Fast-DDS/codecov.yml .
          mkdir coverage-report
          gcovr \
          --root src/Fast-DDS/ \
          --object-directory build/fastrtps \
          --output coverage-report/coverage.xml \
          --xml-pretty \
          --exclude='.*examples/.*' \
          --exclude='.*thirdparty/.*' \
          --exclude='.*test/.*' \
          --exclude='.*/sqlite3.c' \
          --exclude='.*/optionparser.h' \
          --exclude-unreachable-branches

      - name: Upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: coverage-report/
        if: always()

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage-report/coverage.xml
          root_dir: src/Fast-DDS
          fail_ci_if_error: true
