name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - feature/statistics/impl

jobs:
  ubuntu-build-test:
    runs-on: ubuntu-latest
    environment:
      name: codecov

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/Fast-DDS

      - uses: ./src/Fast-DDS/.github/actions/install-apt-packages
      - uses: ./src/Fast-DDS/.github/actions/install-gtest
      - uses: ./src/Fast-DDS/.github/actions/install-python-packages
      - uses: ./src/Fast-DDS/.github/actions/fetch-fastdds-repos

      - name: Update colcon mixin
        run: |
          colcon mixin add default \
            https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon mixin update default
        continue-on-error: true

      - name: Build workspace
        run: |
          pwd
          ls -l
          ls -l src
          ls -l src/Fast-DDS/
          ls -l src/Fast-DDS/.github/
          ls -l src/Fast-DDS/.github/workflows
          cat src/Fast-DDS/.github/workflows/colcon.meta
          colcon build \
            --event-handlers=console_direct+ \
            --metas src/Fast-DDS/.github/workflows/colcon.meta \
            --mixin coverage-gcc

      - name: Run tests
        run: |
          source install/setup.bash && \
          colcon test \
            --packages-select fastrtps \
            --event-handlers=console_direct+

      - name: Generate coverage report
        run: |
          cp src/Fast-DDS/codecov.yml .
          mkdir coverage-report
          gcovr \
          --root src/Fast-DDS/ \
          --object-directory build/fastrtps \
          --output coverage-report/coverage.xml \
          --xml-pretty \
          --exclude='.*examples/.*' \
          --exclude='.*thirdparty/.*' \
          --exclude='.*test/.*' \
          --exclude='.*/sqlite3.c' \
          --exclude='.*/optionparser.h' \
          --exclude-unreachable-branches

      - name: Upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: coverage-report/
        if: always()

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage-report/coverage.xml
          root_dir: src/Fast-DDS
          fail_ci_if_error: true
